### PR TITLE
Fix directory structure

### PR DESCRIPTION
**Pull request by kusnier**
This fixes the directory structure.

### CODE REVIEW

**Comment by AdamBien** [comment]
I'm syncing this project with javaee-bce-pom automatically. Most of your changes were already performed in the  javaee-bce-pom already. Thanks for your contribution!

**Comment by AdamBien** [comment]
Tested several times: mvn archetype:generate always worked for me.

**Comment by kusnier** [comment]
```
$ find . -name Registration.java

./workshops/src/main/java/com/airhacks/workshops/business/registrations/entity/Registration.java
./workshops/src/src/main/java/com/airhacks/workshops/business/registrations/entity/Registration.java
./workshops-st/src/test/java/com/airhacks/workshops/business/registrations/boundary/Registration.java
./workshops-st/test/java/com/airhacks/workshops/business/registrations/boundary/Registration.java
```

```
$ find . -name RegistrationsResource.java

./workshops/src/main/java/com/airhacks/workshops/business/registrations/boundary/RegistrationsResource.java
./workshops/src/src/main/java/com/airhacks/workshops/business/registrations/boundary/RegistrationsResource.java
```

In netbeans the wrong structure is hidden because of the package view.
If you open the Files-View you can find the strange directory structure.

I found the problem in IntelliJ. Here the wrong structure is shown.

Use `Go to File` in Netbeans and enter `RegistrationsResource.java`.
You will find two files. The `Go to Type` will show only one of them.

**Comment by AdamBien** [comment]
Now I found the problem. In addition to regular files, there were some leftovers from earlier releases. I deleted the duplicates. Maven and NetBeans build the project perfectly, because the dups were outside the maven structure. Please try the recent snapshot build -> should work.
Thanks a lot for the hint!

**Comment by kusnier** [comment]
The misplaces files which you have deleted are newer.
The test RegistrationsBoundaryIT#dummy will now fail. Because the left version of Registration has no constructor with id. RegistrationsResource#dummy will now always return a Registration with id 1.

``` java
@GET
@Path("{id}/dummy")
public Registration dummy(@PathParam("id") int registrationId) {
return new Registration(true, 1, 1);
}
```

Sorry for too short initial commit on the pull request.

**Comment by AdamBien** [comment]
Now synced with the current dev branch javaee-bce-pom. Thanks again!

**Pull request closed without merging**
